# Generated by Django 3.1.1 on 2021-09-23 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210608_1557'),
    ]

    operations = [
        migrations.CreateModel(
            name='File_table',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('src', models.CharField(default='None', max_length=200)),
                ('file_name', models.CharField(default='None', max_length=200)),
                ('file_size', models.CharField(default='None', max_length=200)),
                ('file_status', models.SmallIntegerField(choices=[(1, 'off'), (2, 'no')], default=3, verbose_name='文件状态')),
                ('new_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updata_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
        ),
        migrations.RemoveField(
            model_name='config',
            name='Nailed',
        ),
        migrations.RemoveField(
            model_name='config',
            name='project',
        ),
        migrations.RemoveField(
            model_name='d_config',
            name='project',
        ),
        migrations.DeleteModel(
            name='Element_operation',
        ),
        migrations.DeleteModel(
            name='Execution_status',
        ),
        migrations.DeleteModel(
            name='img_code',
        ),
        migrations.DeleteModel(
            name='logic',
        ),
        migrations.RemoveField(
            model_name='nailed',
            name='project',
        ),
        migrations.RemoveField(
            model_name='process',
            name='project',
        ),
        migrations.DeleteModel(
            name='python_txt',
        ),
        migrations.RemoveField(
            model_name='result',
            name='Scenes_id',
        ),
        migrations.RemoveField(
            model_name='result',
            name='project',
        ),
        migrations.RemoveField(
            model_name='scenes',
            name='Config_id',
        ),
        migrations.RemoveField(
            model_name='scenes',
            name='D_Config_id',
        ),
        migrations.RemoveField(
            model_name='scenes',
            name='project',
        ),
        migrations.DeleteModel(
            name='selenium_api',
        ),
        migrations.RemoveField(
            model_name='treegrid',
            name='project',
        ),
        migrations.DeleteModel(
            name='Treegrid_data',
        ),
        migrations.RemoveField(
            model_name='user',
            name='project',
        ),
        migrations.RemoveField(
            model_name='user',
            name='treegrid',
        ),
        migrations.DeleteModel(
            name='Config',
        ),
        migrations.DeleteModel(
            name='D_Config',
        ),
        migrations.DeleteModel(
            name='Nailed',
        ),
        migrations.DeleteModel(
            name='process',
        ),
        migrations.DeleteModel(
            name='project',
        ),
        migrations.DeleteModel(
            name='result',
        ),
        migrations.DeleteModel(
            name='Scenes',
        ),
        migrations.DeleteModel(
            name='Treegrid',
        ),
        migrations.DeleteModel(
            name='user',
        ),
    ]
